<title>Lab 8 - PyTorch and Tensorflow</title>

# Lab 8 - A Dot product and a Matrix Multiplication in PyTorch and Tensorflow
#### Parthasarathy Rajendiran <br>8883828<hr>

### PyTorch

In [1]:
import torch
import helpers as h

Initializing two vecotrs

In [2]:
x = torch.tensor([10., 20., 30.])
y = torch.tensor([5., 15., 25.])
print('Tensor x')
h.print_tensor_info(x)
print('\nTensor y')
h.print_tensor_info(y)

Tensor x
tensor([10., 20., 30.])
Type         <class 'torch.Tensor'>
dtype        torch.float32
Dimension    1
Shape        (3,)

Tensor y
tensor([ 5., 15., 25.])
Type         <class 'torch.Tensor'>
dtype        torch.float32
Dimension    1
Shape        (3,)


Dot product between two vectors

In [3]:
# The expected result is
# 10*5 + 20*15 + 30*25 == 1100
x.dot(y)

tensor(1100.)

Initializing Matrices

In [4]:
mat_a = torch.tensor(
    [
        [1, 9],
        [8, 9]
    ]
)
mat_b = torch.tensor(
    [
        [2, 0],
        [2, 3]
    ]
)

In [5]:
h.print_tensor_info(mat_a)

tensor([[1, 9],
        [8, 9]])
Type         <class 'torch.Tensor'>
dtype        torch.int64
Dimension    2
Shape        (2, 2)


Matrix Multiplication

In [6]:
mat_a @ mat_b

tensor([[20, 27],
        [34, 27]])

---

### TensorFlow

In [1]:
import tensorflow as tf

Redefining same vectors in TensorFlow

In [2]:
x = tf.constant([10., 20., 30.])
y = tf.constant([5., 15., 25.])
print(x)
print(y)

tf.Tensor([10. 20. 30.], shape=(3,), dtype=float32)
tf.Tensor([ 5. 15. 25.], shape=(3,), dtype=float32)


Dot product between two vectors

In [3]:
dot_product = tf.tensordot(x, y, axes=1)
print(dot_product)

tf.Tensor(1100.0, shape=(), dtype=float32)


Redefining the Matrices in TensorFlow

In [4]:
mat_a = tf.constant(
    [
        [1, 9],
        [8, 9]
    ]
)
mat_b = tf.constant(
    [
        [2, 0],
        [2, 3]
    ]
)

print(mat_a)
print(mat_b)

tf.Tensor(
[[1 9]
 [8 9]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[2 0]
 [2 3]], shape=(2, 2), dtype=int32)


Matrix Multiplication

In [5]:
mat_multiplication = mat_a @ mat_b
print(mat_multiplication)

tf.Tensor(
[[20 27]
 [34 27]], shape=(2, 2), dtype=int32)


---